# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\leopo\PycharmProjects\Projet_Info\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(928, 768)
        MainMenu.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\leopo\\PycharmProjects\\Projet_Info\\icone.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainMenu.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.conteneur = QtWidgets.QWidget(self.centralwidget)
        self.conteneur.setGeometry(QtCore.QRect(50, 30, 511, 321))
        self.conteneur.setObjectName("conteneur")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 360, 432, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.NouvelleGrille = QtWidgets.QPushButton(self.widget)
        self.NouvelleGrille.setObjectName("NouvelleGrille")
        self.horizontalLayout_2.addWidget(self.NouvelleGrille)
        spacerItem = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.BouttonQuitter = QtWidgets.QPushButton(self.widget)
        self.BouttonQuitter.setObjectName("BouttonQuitter")
        self.horizontalLayout_2.addWidget(self.BouttonQuitter)
        MainMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainMenu)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(MainMenu)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionNouvelle_Grille = QtWidgets.QAction(MainMenu)
        self.actionNouvelle_Grille.setObjectName("actionNouvelle_Grille")
        self.menuMenu.addAction(self.actionQuitter)
        self.menuMenu.addAction(self.actionNouvelle_Grille)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainMenu)
        self.BouttonQuitter.clicked.connect(MainMenu.close)
        self.actionQuitter.triggered.connect(MainMenu.close)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Sudoku 9000"))
        self.NouvelleGrille.setText(_translate("MainMenu", "Nouvelle Grille"))
        self.BouttonQuitter.setText(_translate("MainMenu", "Quitter"))
        self.menuMenu.setTitle(_translate("MainMenu", "Menu"))
        self.actionQuitter.setText(_translate("MainMenu", "Quitter"))
        self.actionQuitter.setShortcut(_translate("MainMenu", "Ctrl+Q"))
        self.actionNouvelle_Grille.setText(_translate("MainMenu", "Nouvelle Grille"))
        self.actionNouvelle_Grille.setShortcut(_translate("MainMenu", "Ctrl+N"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenu = QtWidgets.QMainWindow()
    ui = Ui_MainMenu()
    ui.setupUi(MainMenu)
    MainMenu.show()
    sys.exit(app.exec_())